export const regions = {
//AMG
    "EL SALTO": "AMG",

    "GUADALAJARA": "AMG",

    "JUANACATLAN": "AMG",

    "SAN PEDRO TLAQUEPAQUE": "AMG",

    "TLAJOMULCO DE ZUÑIGA": "AMG",

    "TONALA": "AMG",

    "ZAPOPAN": "AMG",

    "ZAPOTLANEJO": "AMG",

    // I NORTE

    "BOLAÑOS": "I NORTE",

    "CHIMALTITAN": "I NORTE",

    "COLOTLAN": "I NORTE",

    "HUEJUCAR": "I NORTE",

    "HUEJUQUILLA EL ALTO": "I NORTE",

    "MEZQUITIC": "I NORTE",

    "SAN MARTIN DE BOLAÑOS": "I NORTE",

    "SANTA MARIA DE LOS ANGELES": "I NORTE",

    "TOTATICHE": "I NORTE",

    "VILLA GUERRERO": "I NORTE",

    // II ALTOS NORTE 

    "ENCARNACION DE DIAZ": "II ALTOS NORTE",

    "LAGOS DE MORENO": "II ALTOS NORTE",

    "OJUELOS DE JALISCO": "II ALTOS NORTE",

    "SAN DIEGO DE ALEJANDRIA": "II ALTOS NORTE",

    "SAN JUAN DE LOS LAGOS": "II ALTOS NORTE",

    "TEOCALTICHE": "II ALTOS NORTE",

    "UNION DE SAN ANTONIO": "II ALTOS NORTE",

    "VILLA HIDALGO": "II ALTOS NORTE",

//III ALTOS SUR 
    "ACATIC": "III ALTOS SUR",

    "ARANDAS": "III ALTOS SUR",

    "CAÑADAS DE OBREGON": "III ALTOS SUR",

    "CUQUIO": "III ALTOS SUR",

    "JALOSTOTITLAN": "III ALTOS SUR",

    "JESUS MARIA": "III ALTOS SUR",

    "MEXTICACAN": "III ALTOS SUR",

    "SAN IGNACIO CERRO GORDO": "III ALTOS SUR",

    "SAN JULIAN": "III ALTOS SUR",

    "SAN MIGUEL EL ALTO": "III ALTOS SUR",

    "TEPATITLAN DE MORELOS": "III ALTOS SUR",

    "VALLE DE GUADALUPE": "III ALTOS SUR",

    "YAHUALICA DE GONZALEZ GALLO": "III ALTOS SUR",

//IV CIENEGA 
    "ATOTONILCO EL ALTO": "IV CIÉNEGA",

    "AYOTLAN": "IV CIÉNEGA",

    "DEGOLLADO": "IV CIÉNEGA",

    "JAMAY": "IV CIÉNEGA",

    "LA BARCA": "IV CIÉNEGA",

    "OCOTLAN": "IV CIÉNEGA",

    "PONCITLAN": "IV CIÉNEGA",

    "TOTOTLAN": "IV CIÉNEGA",

    "ZAPOTLAN DEL REY": "IV CIÉNEGA",

//IX COSTA NORTE 

    "CABO CORRIENTES": "IX COSTA NORTE",

    "PUERTO VALLARTA": "IX COSTA NORTE",

    "TOMATLAN": "IX COSTA NORTE",

//V SURESTE 
    "CONCEPCION DE BUENOS AIRES": "V SURESTE",

    "JILOTLAN DE LOS DOLORES": "V SURESTE",

    "LA MANZANILLA DE LA PAZ": "V SURESTE",

    "MAZAMITLA": "V SURESTE",

    "PIHUAMO": "V SURESTE",

    "QUITUPAN": "V SURESTE",

    "SANTA MARIA DEL ORO": "V SURESTE",

    "TAMAZULA DE GORDIANO": "V SURESTE",

    "TECALITLAN": "V SURESTE",

    "VALLE DE JUAREZ": "V SURESTE",

//VI SUR 
    "AMACUECA": "VI SUR",

    "ATEMAJAC DE BRIZUELA": "VI SUR",

    "ATOYAC": "VI SUR",

    "GOMEZ FARIAS": "VI SUR",

    "SAN GABRIEL": "VI SUR",

    "SAYULA": "VI SUR",

    "TAPALPA": "VI SUR",

    "TECHALUTA DE MONTENEGRO": "VI SUR",

    "TEOCUITATLAN DE CORONA": "VI SUR",

    "TOLIMAN": "VI SUR",

    "TONILA": "VI SUR",

    "TUXPAN": "VI SUR",

    "ZACOALCO DE TORRES": "VI SUR",

    "ZAPOTILTIC": "VI SUR",

    "ZAPOTITLAN DE VADILLO": "VI SUR",

    "ZAPOTLAN EL GRANDE": "VI SUR",

//VII SIERRA DE AMULA 

    "ATENGO": "VII SIERRA DE AMULA",

    "CHIQUILISTLAN": "VII SIERRA DE AMULA",

    "EJUTLA": "VII SIERRA DE AMULA",

    "EL GRULLO": "VII SIERRA DE AMULA",

    "EL LIMON": "VII SIERRA DE AMULA",

    "JUCHITLAN": "VII SIERRA DE AMULA",

    "TECOLOTLAN": "VII SIERRA DE AMULA",

    "TENAMAXTLAN": "VII SIERRA DE AMULA",

    "TONAYA": "VII SIERRA DE AMULA",

    "TUXCACUESCO": "VII SIERRA DE AMULA",

    "UNION DE TULA": "VII SIERRA DE AMULA",

//VIII COSTA SUR

    "AUTLAN DE NAVARRO": "VIII COSTA SUR",

    "CASIMIRO CASTILLO": "VIII COSTA SUR",

    "CIHUATLAN": "VIII COSTA SUR",

    "CUAUTITLAN DE GARCIA BARRAGAN": "VIII COSTA SUR",

    "LA HUERTA": "VIII COSTA SUR",

    "VILLA PURIFICACION": "VIII COSTA SUR",

    "ATENGUILLO": "X SIERRA OCCIDENTAL",

    "AYUTLA": "X SIERRA OCCIDENTAL",

    "CUAUTLA": "X SIERRA OCCIDENTAL",

    "GUACHINANGO": "X SIERRA OCCIDENTAL",

    "MASCOTA": "X SIERRA OCCIDENTAL",

    "MIXTLAN": "X SIERRA OCCIDENTAL",

    "SAN SEBASTIAN DEL OESTE": "X SIERRA OCCIDENTAL",

    "TALPA DE ALLENDE": "X SIERRA OCCIDENTAL",

    "AHUALULCO DE MERCADO": "XI VALLES",

    "AMATITAN": "XI VALLES",

    "AMECA": "XI VALLES",

    "COCULA": "XI VALLES",

    "EL ARENAL": "XI VALLES",

    "ETZATLAN": "XI VALLES",

    "HOSTOTIPAQUILLO": "XI VALLES",

    "MAGDALENA": "XI VALLES",

    "SAN JUANITO DE ESCOBEDO": "XI VALLES",

    "SAN MARCOS": "XI VALLES",

    "SAN MARTIN HIDALGO": "XI VALLES",

    "TALA": "XI VALLES",

    "TEQUILA": "XI VALLES",

    "TEUCHITLAN": "XI VALLES",

    "ACATLAN DE JUAREZ": "XII CENTRO",
    
    "CHAPALA": "XII CENTRO",

    "IXLAHUACAN DEL RIO": "XII CENTRO",

    "JOCOTEPEC": "XII CENTRO",

    "SAN CRISTOBAL DE LA BARRANCA": "XII CENTRO",

    "TIZAPAN EL ALTO": "XII CENTRO",

    "TUXCUECA": "XII CENTRO",

    "VILLA CORONA": "XII CENTRO",

    "ZZSE IGNORA": "ZZSE IGNORA"
}